# Generated by Django 2.2.12 on 2020-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='kjj',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
